### ISSUE TITLE
Get error when trying to run the script.

### ISSUE THREAD

**Issue by vinhloc1996** [PeterEsenwa/PluralSight-Playlist-Downloader#1]
I have tried to run the script but it shows the error in the console:

![image](https://user-images.githubusercontent.com/17821665/28400248-045e6334-6d3c-11e7-9ba7-5636d70fe41d.png)

Is there any way to fix this?

**Comment by vinhloc1996** [comment]
Update: I have disabled the web security but it still gets the same error when I try to run the script.

I had using this script in the batch file:

```
TASKKILL /F /IM chrome.exe
start chrome.exe --args --disable-web-security
pause
```

Any other ways?

**Comment by PeterEsenwa** [comment]
When you load the script and get this error, a shield should appear in your chrome somewhere to the far right of the address bar. Click it and allow unsafe script/content.

**Comment by vinhloc1996** [comment]
Thank you, I haven't tried it yet but I have figured out another way to download the video in PluralSight.
